kind: Service
apiVersion: v1
metadata:
  labels:
      name: catalog-b
      role: backend
  name: catalog
spec:
  ports:
    - name: catalog
      port: 7777
      targetPort: 80
  externalIPs: [192.168.99.104]
  type: LoadBalancer
  selector:
      app: catalog