apiVersion: v1
kind: ReplicationController
metadata:
  name: catalog
spec:
  replicas: 1
  selector:
    name: catalog
  template:
    metadata:
      labels:
        name: catalog
        role: frontend
        app: catalog
      name: catalog
    spec:
      containers:
        - name: catalog
          image: zutherb/catalog-frontend
          ports:
            - containerPort: 80
          env:
            - name: CHECKOUT_DESIGN
              value: "standard"