apiVersion: v1
kind: ReplicationController
metadata:
  name: product
spec:
  replicas: 1
  selector:
    name: product
  template:
    metadata:
      labels:
        name: product
        role: backend
      name: product
    spec:
      containers:
        - name: product
          image: zutherb/product-service
          ports:
            - containerPort: 18080