apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    name: redis
  template:
    metadata:
      labels:
        name: redis
        role: database
      name: redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379