apiVersion: v1
kind: Service
metadata:
  labels:
    app: r-shiny
  name: r-shiny
spec:
  type: NodePort
  ports:
  - name: http
    port: 3838
    protocol: TCP
    targetPort: 3838
  selector:
    app: r-shiny
